import { useState, useEffect, useRef, useCallback, createContext, useContext } from 'react'
import { motion, AnimatePresence, useMotionValue, useSpring, useInView } from 'framer-motion'
import { DS, FONTS } from '../lib/design.js'

export function MagneticCursor(){const cx=useMotionValue(-100),cy=useMotionValue(-100),rx=useSpring(cx,{stiffness:130,damping:22}),ry=useSpring(cy,{stiffness:130,damping:22}),[hov,setHov]=useState(false),[click,setClick]=useState(false);useEffect(()=>{const mv=e=>{cx.set(e.clientX);cy.set(e.clientY)},mo=e=>setHov(!!e.target.closest('button,a,[data-hover]')),md=()=>setClick(true),mu=()=>setClick(false);window.addEventListener('mousemove',mv);window.addEventListener('mouseover',mo);window.addEventListener('mousedown',md);window.addEventListener('mouseup',mu);return()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseover',mo);window.removeEventListener('mousedown',md);window.removeEventListener('mouseup',mu)}},[]);return(<><motion.div style={{position:'fixed',top:0,left:0,pointerEvents:'none',zIndex:9999,width:8,height:8,borderRadius:'50%',background:DS.lime,mixBlendMode:'exclusion',x:cx,y:cy,translateX:'-50%',translateY:'-50%'}} animate={{scale:click?.4:hov?1.8:1}} transition={{duration:.12}}/><motion.div style={{position:'fixed',top:0,left:0,pointerEvents:'none',zIndex:9998,borderRadius:'50%',border:`1px solid ${hov?DS.lime:'rgba(184,255,0,.3)'}`,x:rx,y:ry,translateX:'-50%',translateY:'-50%',transition:'width .2s,height .2s,border-color .2s'}} animate={{width:hov?52:34,height:hov?52:34}}/></>)}
export function NoiseOverlay(){return <div style={{position:'fixed',inset:0,pointerEvents:'none',zIndex:1,backgroundImage:`url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.03'/%3E%3C/svg%3E")`,backgroundRepeat:'repeat',backgroundSize:'128px',opacity:.5}}/>}
export function Badge({label,type='ok',size='sm'}){const colors={ok:{bg:`${DS.green}15`,border:`${DS.green}35`,text:DS.green},warn:{bg:`${DS.gold}15`,border:`${DS.gold}35`,text:DS.gold},danger:{bg:`${DS.red}15`,border:`${DS.red}35`,text:DS.red},info:{bg:`${DS.blue}15`,border:`${DS.blue}35`,text:DS.blue},lime:{bg:`${DS.lime}15`,border:`${DS.lime}35`,text:DS.lime},neutral:{bg:`${DS.gray}15`,border:`${DS.gray}35`,text:DS.gray3}};const c=colors[type]||colors.ok;return <span style={{display:'inline-block',padding:size==='sm'?'2px 8px':'4px 12px',borderRadius:4,background:c.bg,border:`1px solid ${c.border}`,color:c.text,fontSize:size==='sm'?'.62rem':'.75rem',fontWeight:700,letterSpacing:'.1em',textTransform:'uppercase',fontFamily:FONTS.mono}}>{label}</span>}
export function BtnPrimary({label,onClick,href,small,full,icon,disabled,loading}){const[hov,setHov]=useState(false);const style={display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8,padding:small?'8px 18px':'13px 28px',borderRadius:DS.r2,border:'none',background:disabled?DS.gray:hov?DS.lime2:DS.lime,color:DS.bg,fontFamily:FONTS.body,fontWeight:700,fontSize:small?'.8rem':'.92rem',letterSpacing:'.02em',cursor:'pointer',transition:'all .2s',width:full?'100%':'auto',boxShadow:hov&&!disabled?`0 6px 28px rgba(184,255,0,.35)`:'none',transform:hov&&!disabled?'translateY(-2px)':'none',opacity:disabled?.5:1,textDecoration:'none'};const inner=<>{loading&&<Spinner size={14} color={DS.bg}/>}{icon&&!loading&&<span style={{fontSize:'1rem'}}>{icon}</span>}{label}</>;if(href)return <motion.a href={href} onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} whileTap={{scale:.96}} style={style}>{inner}</motion.a>;return <motion.button onClick={onClick} onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} whileTap={{scale:.96}} disabled={disabled||loading} style={style}>{inner}</motion.button>}
export function BtnGhost({label,onClick,href,small,full,color}){const[hov,setHov]=useState(false);const c=color||DS.gray3;const style={display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8,padding:small?'7px 16px':'12px 26px',borderRadius:DS.r2,background:hov?`${DS.lime}08`:'transparent',border:`1px solid ${hov?DS.lime+'55':DS.border}`,color:hov?DS.white:c,fontFamily:FONTS.body,fontWeight:500,fontSize:small?'.8rem':'.92rem',cursor:'pointer',transition:'all .2s',width:full?'100%':'auto',textDecoration:'none'};if(href)return <motion.a href={href} onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} whileTap={{scale:.96}} style={style}>{label}</motion.a>;return <motion.button onClick={onClick} onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} whileTap={{scale:.96}} style={style}>{label}</motion.button>}
export function Spinner({size=18,color=DS.lime}){return <motion.span animate={{rotate:360}} transition={{duration:.8,repeat:Infinity,ease:'linear'}} style={{display:'block',width:size,height:size,borderRadius:'50%',border:`2px solid ${color}22`,borderTopColor:color,flexShrink:0}}/>}

const inputBase={width:'100%',padding:'10px 14px',background:DS.bg2,border:`1px solid ${DS.border}`,borderRadius:DS.r,color:DS.white,fontFamily:FONTS.body,fontSize:'.9rem',outline:'none',transition:'border-color .2s,box-shadow .2s'}
export function Input({value,onChange,placeholder,type='text',name}){return <input name={name} type={type} value={value} onChange={onChange} placeholder={placeholder} style={inputBase} onFocus={e=>{e.target.style.borderColor=DS.lime;e.target.style.boxShadow=`0 0 0 3px ${DS.lime}12`}} onBlur={e=>{e.target.style.borderColor=DS.border;e.target.style.boxShadow='none'}}/>}
export function Textarea({value,onChange,placeholder,rows=4}){return <textarea value={value} onChange={onChange} placeholder={placeholder} rows={rows} style={{...inputBase,resize:'vertical',minHeight:rows*26}} onFocus={e=>{e.target.style.borderColor=DS.lime;e.target.style.boxShadow=`0 0 0 3px ${DS.lime}12`}} onBlur={e=>{e.target.style.borderColor=DS.border;e.target.style.boxShadow='none'}}/>}
export function Select({value,onChange,children,placeholder}){return <select value={value} onChange={onChange} style={{...inputBase,cursor:'pointer',appearance:'none',backgroundImage:`url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'%3E%3Cpath fill='%23606888' d='M6 8L0 0h12z'/%3E%3C/svg%3E")`,backgroundRepeat:'no-repeat',backgroundPosition:'right 14px center'}} onFocus={e=>e.target.style.borderColor=DS.lime} onBlur={e=>e.target.style.borderColor=DS.border}>{placeholder&&<option value=''>{placeholder}</option>}{children}</select>}
export function Toggle({value,onChange,label}){return <label style={{display:'flex',alignItems:'center',gap:12,cursor:'pointer'}}><div onClick={()=>onChange(!value)} style={{width:42,height:22,borderRadius:11,background:value?DS.lime:DS.border,position:'relative',transition:'background .25s',flexShrink:0}}><motion.div animate={{x:value?22:2}} transition={{type:'spring',stiffness:500,damping:32}} style={{position:'absolute',top:2,width:18,height:18,borderRadius:'50%',background:value?DS.bg:DS.gray3}}/></div>{label&&<span style={{fontFamily:FONTS.body,fontSize:'.88rem',color:DS.gray3}}>{label}</span>}</label>}

export function Section({id,children,bg,style={}}){return <section id={id} style={{background:bg||DS.bg,padding:'7rem 0',position:'relative',overflow:'hidden',...style}}>{children}</section>}
export function Container({children,style={}}){return <div style={{maxWidth:1680,width:'100%',margin:'0 auto',padding:'0 clamp(1.25rem,4vw,3.5rem)',position:'relative',zIndex:2,boxSizing:'border-box',...style}}>{children}</div>}
export function SectionHeader({eyebrow,title,titleHighlight,desc,center}){return(<div style={{marginBottom:'3.5rem',textAlign:center?'center':'left'}}><div style={{display:'flex',alignItems:'center',justifyContent:center?'center':'flex-start',gap:10,marginBottom:'1rem'}}>{!center&&<span style={{width:28,height:1,background:DS.lime,display:'block'}}/>}<span style={{fontFamily:FONTS.mono,fontSize:'.68rem',color:DS.lime,letterSpacing:'.16em',textTransform:'uppercase',fontWeight:600}}>{eyebrow}</span>{center&&<span style={{width:28,height:1,background:DS.lime,display:'block'}}/>}</div><h2 style={{fontFamily:FONTS.display,fontWeight:800,fontSize:'clamp(2rem,4vw,3.5rem)',color:DS.white,lineHeight:1.1,letterSpacing:'-.01em',marginBottom:'1rem'}}>{title}{' '}{titleHighlight&&<span style={{color:DS.lime}}>{titleHighlight}</span>}</h2>{desc&&<p style={{fontFamily:FONTS.body,color:DS.gray3,fontSize:'1rem',lineHeight:1.8,fontWeight:300,maxWidth:center?560:'100%',margin:center?'0 auto':0}}>{desc}</p>}</div>)}
export function Card({children,style={},onClick,hoverable=true}){const[hov,setHov]=useState(false);return <motion.div onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} onClick={onClick} animate={hoverable?{borderColor:hov?`${DS.lime}44`:DS.border,y:hov?-5:0}:{}} transition={{duration:.25}} style={{background:DS.surface,border:`1px solid ${DS.border}`,borderRadius:DS.r3,overflow:'hidden',boxShadow:hoverable&&hov?`0 16px 48px rgba(0,0,0,.5)`:'none',cursor:onClick?'none':'default',...style}}>{children}</motion.div>}
export function HudBrackets({color=DS.lime,size=10,w=1.5}){const b=`${w}px solid ${color}`,s={position:'absolute',width:size,height:size};return(<><span style={{...s,top:0,left:0,borderTop:b,borderLeft:b}}/><span style={{...s,top:0,right:0,borderTop:b,borderRight:b}}/><span style={{...s,bottom:0,left:0,borderBottom:b,borderLeft:b}}/><span style={{...s,bottom:0,right:0,borderBottom:b,borderRight:b}}/></>)}
export function Reveal({children,delay=0,x=0,y=28,style={}}){const ref=useRef(null),inView=useInView(ref,{once:true,margin:'-60px'});return <motion.div ref={ref} initial={{opacity:0,y,x,filter:'blur(6px)'}} animate={inView?{opacity:1,y:0,x:0,filter:'blur(0px)'}:{}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}} style={style}>{children}</motion.div>}
export function Counter({target,duration=2}){const[val,setVal]=useState(0),ref=useRef(null),inView=useInView(ref,{once:true});useEffect(()=>{if(!inView)return;const num=parseInt(target);if(isNaN(num))return;const start=Date.now(),tick=()=>{const el=(Date.now()-start)/1000,pr=Math.min(el/duration,1),ea=1-Math.pow(1-pr,3);setVal(Math.floor(ea*num));if(pr<1)requestAnimationFrame(tick);else setVal(num)};requestAnimationFrame(tick)},[inView,target,duration]);const suf=target?.toString().includes('+')?'+':target?.toString().includes('%')?'%':'';return <span ref={ref}>{!isNaN(parseInt(target))?val+suf:target}</span>}
export function FormGroup({label,required,children}){return <div><label style={{display:'block',fontFamily:FONTS.mono,fontSize:'.62rem',fontWeight:600,color:DS.gray3,letterSpacing:'.12em',textTransform:'uppercase',marginBottom:'.45rem'}}>{label}{required&&<span style={{color:DS.lime,marginLeft:4}}>*</span>}</label>{children}</div>}
export function AdminTable({cols,rows,emptyMsg='Aucune donnée'}){return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{cols.map(c=><th key={c.key||c.label} style={{padding:'8px 14px',textAlign:'left',fontSize:'.62rem',fontWeight:700,textTransform:'uppercase',letterSpacing:'.14em',color:DS.gray2,background:DS.bg2,borderBottom:`1px solid ${DS.border}`,fontFamily:FONTS.mono}}>{c.label}</th>)}</tr></thead><tbody>{rows.length===0?<tr><td colSpan={cols.length} style={{padding:'2rem',textAlign:'center',color:DS.gray,fontFamily:FONTS.mono,fontSize:'.75rem'}}>{emptyMsg}</td></tr>:rows.map((row,ri)=><tr key={ri} style={{borderBottom:`1px solid ${DS.border}`}} onMouseEnter={e=>e.currentTarget.style.background=`${DS.lime}04`} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>{cols.map(c=><td key={c.key||c.label} style={{padding:'10px 14px',fontSize:'.82rem',color:c.bold?DS.white:DS.gray3,fontWeight:c.bold?600:400,fontFamily:FONTS.body}}>{c.render?c.render(row):row[c.key]}</td>)}</tr>)}</tbody></table></div>}
export function AdminPanel({title,action,children}){return <div style={{background:DS.surface,border:`1px solid ${DS.border}`,borderRadius:DS.r2,overflow:'hidden',marginBottom:'1.5rem'}}><div style={{padding:'10px 16px',borderBottom:`1px solid ${DS.border}`,display:'flex',alignItems:'center',justifyContent:'space-between',background:DS.bg2}}><span style={{fontSize:'.72rem',fontWeight:700,color:DS.gray3,letterSpacing:'.1em',textTransform:'uppercase',fontFamily:FONTS.mono}}>{title}</span>{action}</div>{children}</div>}
export function AdminFormPanel({show,children}){return <AnimatePresence>{show&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.35,ease:[.22,1,.36,1]}} style={{overflow:'hidden',borderBottom:`1px solid ${DS.border}`,background:DS.bg3}}><div style={{padding:'1.25rem'}}>{children}</div></motion.div>}</AnimatePresence>}
export function StatCard({label,value,sub,color,index=0}){const ref=useRef(null),inView=useInView(ref,{once:true});return <motion.div ref={ref} initial={{opacity:0,y:16}} animate={inView?{opacity:1,y:0}:{}} transition={{delay:index*.08,duration:.5}} style={{background:DS.surface,border:`1px solid ${DS.border}`,borderRadius:DS.r2,padding:'1.5rem',borderTop:`2px solid ${color}`,position:'relative',overflow:'hidden'}}><motion.div animate={{y:['-100%','200%']}} transition={{duration:4,repeat:Infinity,ease:'linear',delay:index*.6}} style={{position:'absolute',left:0,right:0,height:'30%',background:`linear-gradient(to bottom,transparent,${color}08,transparent)`,pointerEvents:'none'}}/><div style={{fontFamily:FONTS.mono,fontSize:'.6rem',color:DS.gray2,letterSpacing:'.14em',textTransform:'uppercase',marginBottom:'.5rem'}}>{label}</div><div style={{fontFamily:FONTS.display,fontWeight:800,fontSize:'1.8rem',color,lineHeight:1,marginBottom:'.25rem'}}>{value}</div>{sub&&<div style={{fontSize:'.72rem',color:DS.gray3,fontFamily:FONTS.mono}}>{sub}</div>}</motion.div>}
export function AdminBtn({label,onClick,variant='lime',small}){const[hov,setHov]=useState(false);const bg={lime:DS.lime,ghost:'transparent',red:DS.red,gold:DS.gold}[variant];return <motion.button onClick={onClick} onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} whileTap={{scale:.94}} style={{padding:small?'5px 10px':'8px 16px',borderRadius:4,cursor:'pointer',fontFamily:FONTS.mono,fontSize:small?'.62rem':'.72rem',fontWeight:700,letterSpacing:'.08em',background:variant==='ghost'?(hov?DS.s2:DS.bg2):(hov?bg+'CC':bg),border:variant==='ghost'?`1px solid ${DS.b2}`:'none',color:variant==='ghost'?(hov?DS.white:DS.gray3):DS.bg,transition:'all .15s',display:'inline-flex',alignItems:'center',gap:5}}>{label}</motion.button>}

export function WhatsAppFloat(){const[vis,setVis]=useState(false),[hov,setHov]=useState(false);useEffect(()=>{const t=setTimeout(()=>setVis(true),2500);return()=>clearTimeout(t)},[]);return <AnimatePresence>{vis&&<motion.div initial={{opacity:0,scale:0}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:0}} transition={{type:'spring',stiffness:300,damping:24}} style={{position:'fixed',bottom:'2rem',left:'2rem',zIndex:800,display:'flex',alignItems:'center',gap:10}}><motion.a href="https://wa.me/237683421271?text=Bonjour%20INFO-TECH%2C%20je%20souhaite%20en%20savoir%20plus%20sur%20vos%20services." target="_blank" rel="noopener noreferrer" onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} whileHover={{scale:1.1}} whileTap={{scale:.92}} style={{width:54,height:54,borderRadius:'50%',background:'#25D366',display:'flex',alignItems:'center',justifyContent:'center',position:'relative',boxShadow:'0 4px 20px rgba(37,211,102,.4)'}}><svg width="26" height="26" viewBox="0 0 24 24" fill="white"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/></svg><motion.div animate={{scale:[1,1.6],opacity:[.5,0]}} transition={{duration:1.8,repeat:Infinity,ease:'easeOut'}} style={{position:'absolute',width:54,height:54,borderRadius:'50%',border:'2px solid #25D366',pointerEvents:'none'}}/></motion.a><AnimatePresence>{hov&&<motion.div initial={{opacity:0,x:-8}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-8}} style={{background:DS.surface,border:`1px solid ${DS.border}`,borderRadius:DS.r2,padding:'.6rem 1rem',fontFamily:FONTS.body,fontSize:'.82rem',color:DS.white,whiteSpace:'nowrap'}}>Discuter sur WhatsApp →</motion.div>}</AnimatePresence></motion.div>}</AnimatePresence>}

const ToastCtx=createContext(null)
export const useToast=()=>useContext(ToastCtx)
export function ToastProvider({children}){const[toasts,setToasts]=useState([]);const push=useCallback((msg,type='ok')=>{const id=Date.now();setToasts(p=>[...p,{id,msg,type}]);setTimeout(()=>setToasts(p=>p.filter(t=>t.id!==id)),3400)},[]);return <ToastCtx.Provider value={push}>{children}<div style={{position:'fixed',bottom:'2rem',right:'2rem',zIndex:9000,display:'flex',flexDirection:'column',gap:8,pointerEvents:'none'}}><AnimatePresence>{toasts.map(t=><motion.div key={t.id} initial={{opacity:0,x:60,scale:.9}} animate={{opacity:1,x:0,scale:1}} exit={{opacity:0,x:60,scale:.9}} transition={{type:'spring',stiffness:400,damping:28}} style={{background:DS.surface,border:`1px solid ${t.type==='ok'?DS.lime+'44':t.type==='warn'?DS.gold+'44':DS.red+'44'}`,borderRadius:DS.r2,padding:'10px 18px',fontFamily:FONTS.mono,fontSize:'.78rem',color:t.type==='ok'?DS.lime:t.type==='warn'?DS.gold:DS.red,display:'flex',alignItems:'center',gap:10,whiteSpace:'nowrap'}}><span style={{width:6,height:6,borderRadius:'50%',background:t.type==='ok'?DS.lime:t.type==='warn'?DS.gold:DS.red,flexShrink:0}}/>{t.msg}</motion.div>)}</AnimatePresence></div></ToastCtx.Provider>}

const CartCtx=createContext(null)
export const useCart=()=>useContext(CartCtx)
export function CartProvider({children}){const[items,setItems]=useState([]);const add=useCallback((p)=>setItems(prev=>{const ex=prev.find(i=>i.id===p.id);return ex?prev.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...prev,{...p,qty:1}]}),[]);const remove=useCallback((id)=>setItems(p=>p.filter(i=>i.id!==id)),[]);const setQty=useCallback((id,qty)=>{if(qty<1){remove(id);return};setItems(p=>p.map(i=>i.id===id?{...i,qty}:i))},[]);const clear=useCallback(()=>setItems([]),[]);const total=items.reduce((s,i)=>s+i.price*i.qty,0);const count=items.reduce((s,i)=>s+i.qty,0);return <CartCtx.Provider value={{items,add,remove,setQty,clear,total,count}}>{children}</CartCtx.Provider>}
